<?php
/**
 * InlineResponse2005Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  WhatsAppChatApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Chat API SDK
 *
 * The SDK allows you to receive and send messages through your WhatsApp account. [Sign up now](https://app.chat-api.com/)  The Chat API is based on the WhatsApp WEB protocol and excludes the ban both when using libraries from mgp25 and the like. Despite this, your account can be banned by anti-spam system WhatsApp after several clicking the \"block\" button.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sale@chat-api.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace WhatsAppChatApi;

use PHPUnit\Framework\TestCase;

/**
 * InlineResponse2005Test Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse2005
 * @package     WhatsAppChatApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class InlineResponse2005Test extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse2005"
     */
    public function testInlineResponse2005()
    {
    }

    /**
     * Test attribute "webhook_url"
     */
    public function testPropertyWebhookUrl()
    {
    }

    /**
     * Test attribute "ack_notifications_on"
     */
    public function testPropertyAckNotificationsOn()
    {
    }

    /**
     * Test attribute "chat_update_on"
     */
    public function testPropertyChatUpdateOn()
    {
    }

    /**
     * Test attribute "video_upload_on"
     */
    public function testPropertyVideoUploadOn()
    {
    }

    /**
     * Test attribute "proxy"
     */
    public function testPropertyProxy()
    {
    }

    /**
     * Test attribute "guaranteed_hooks"
     */
    public function testPropertyGuaranteedHooks()
    {
    }

    /**
     * Test attribute "ignore_old_messages"
     */
    public function testPropertyIgnoreOldMessages()
    {
    }

    /**
     * Test attribute "process_archive"
     */
    public function testPropertyProcessArchive()
    {
    }

    /**
     * Test attribute "instance_statuses"
     */
    public function testPropertyInstanceStatuses()
    {
    }

    /**
     * Test attribute "webhook_statuses"
     */
    public function testPropertyWebhookStatuses()
    {
    }

    /**
     * Test attribute "status_notifications_on"
     */
    public function testPropertyStatusNotificationsOn()
    {
    }

    /**
     * Test attribute "update"
     */
    public function testPropertyUpdate()
    {
    }
}
