<?php
/**
 * Class6BanApiTest
 * PHP version 5
 *
 * @category Class
 * @package  WhatsAppChatApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Chat API SDK
 *
 * The SDK allows you to receive and send messages through your WhatsApp account. [Sign up now](https://app.chat-api.com/)  The Chat API is based on the WhatsApp WEB protocol and excludes the ban both when using libraries from mgp25 and the like. Despite this, your account can be banned by anti-spam system WhatsApp after several clicking the \"block\" button.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sale@chat-api.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace WhatsAppChatApi;

use \WhatsAppChatApi\Configuration;
use \WhatsAppChatApi\ApiException;
use \WhatsAppChatApi\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * Class6BanApiTest Class Doc Comment
 *
 * @category Class
 * @package  WhatsAppChatApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Class6BanApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for banTest
     *
     * Test ban settings.
     *
     */
    public function testBanTest()
    {
    }

    /**
     * Test case for getBanSettings
     *
     * Get settings.
     *
     */
    public function testGetBanSettings()
    {
    }

    /**
     * Test case for setBanSettings
     *
     * Set settings.
     *
     */
    public function testSetBanSettings()
    {
    }
}
