<?php
/**
 * Class2MessagesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  WhatsAppChatApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Chat API SDK
 *
 * The SDK allows you to receive and send messages through your WhatsApp account. [Sign up now](https://app.chat-api.com/)  The Chat API is based on the WhatsApp WEB protocol and excludes the ban both when using libraries from mgp25 and the like. Despite this, your account can be banned by anti-spam system WhatsApp after several clicking the \"block\" button.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sale@chat-api.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace WhatsAppChatApi;

use \WhatsAppChatApi\Configuration;
use \WhatsAppChatApi\ApiException;
use \WhatsAppChatApi\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * Class2MessagesApiTest Class Doc Comment
 *
 * @category Class
 * @package  WhatsAppChatApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Class2MessagesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for forwardMessage
     *
     * Forwarding messages to a new or existing chat..
     *
     */
    public function testForwardMessage()
    {
    }

    /**
     * Test case for getMessages
     *
     * Get a list of messages..
     *
     */
    public function testGetMessages()
    {
    }

    /**
     * Test case for sendContact
     *
     * Sending a contact or contact list to a new or existing chat..
     *
     */
    public function testSendContact()
    {
    }

    /**
     * Test case for sendFile
     *
     * Send a file to a new or existing chat..
     *
     */
    public function testSendFile()
    {
    }

    /**
     * Test case for sendLink
     *
     * Send text with link and link's preview to a new or existing chat..
     *
     */
    public function testSendLink()
    {
    }

    /**
     * Test case for sendLocation
     *
     * Sending a location to a new or existing chat..
     *
     */
    public function testSendLocation()
    {
    }

    /**
     * Test case for sendMessage
     *
     * Send a message to a new or existing chat..
     *
     */
    public function testSendMessage()
    {
    }

    /**
     * Test case for sendPTT
     *
     * Send a ptt-audio to a new or existing chat..
     *
     */
    public function testSendPTT()
    {
    }

    /**
     * Test case for sendVCard
     *
     * Sending a vcard to a new or existing chat..
     *
     */
    public function testSendVCard()
    {
    }
}
